# fly.toml app configuration file generated for floral-haze-4013 on 2023-04-24T21:56:45+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "floral-haze-4013"
primary_region = "sin"

[env]
  PORT = "3000"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
